import { User } from "@/types/User";

// TODO: Remove mocks
export const useUsers = () => {
    const data: User[] = [
        {
            id: 1,
            firstName: "John",
            lastName: "Doe",
            login: "johndoe",
            dateOfBirth: new Date(1990, 5, 15),
            role: "Admin",
            isActive: true,
        },
        {
            id: 2,
            firstName: "Jane",
            lastName: "Smith",
            login: "janesmith",
            dateOfBirth: new Date(1985, 8, 22),
            role: "User",
            isActive: true,
        },
        {
            id: 3,
            firstName: "Michael",
            lastName: "Johnson",
            login: "michaelj",
            dateOfBirth: new Date(1992, 2, 10),
            role: "User",
            isActive: false,
        },
        {
            id: 4,
            firstName: "Emily",
            lastName: "Williams",
            login: "emilyw",
            dateOfBirth: new Date(1988, 11, 5),
            role: "Admin",
            isActive: true,
        },
        {
            id: 5,
            firstName: "Robert",
            lastName: "Brown",
            login: "robertb",
            dateOfBirth: new Date(1995, 4, 30),
            role: "User",
            isActive: true,
        },
        {
            id: 6,
            firstName: "Sarah",
            lastName: "Davis",
            login: "sarahd",
            dateOfBirth: new Date(1991, 7, 18),
            role: "User",
            isActive: false,
        },
        {
            id: 7,
            firstName: "David",
            lastName: "Miller",
            login: "davidm",
            dateOfBirth: new Date(1987, 1, 25),
            role: "Admin",
            isActive: true,
        },
        {
            id: 8,
            firstName: "Jennifer",
            lastName: "Wilson",
            login: "jenniferw",
            dateOfBirth: new Date(1993, 9, 12),
            role: "User",
            isActive: true,
        },
        {
            id: 9,
            firstName: "Thomas",
            lastName: "Moore",
            login: "thomasm",
            dateOfBirth: new Date(1989, 6, 8),
            role: "User",
            isActive: false,
        },
        {
            id: 10,
            firstName: "Lisa",
            lastName: "Taylor",
            login: "lisat",
            dateOfBirth: new Date(1994, 3, 20),
            role: "Admin",
            isActive: true,
        },
        {
            id: 11,
            firstName: "James",
            lastName: "Anderson",
            login: "jamesa",
            dateOfBirth: new Date(1986, 10, 14),
            role: "User",
            isActive: true,
        },
        {
            id: 12,
            firstName: "Amanda",
            lastName: "Thomas",
            login: "amandat",
            dateOfBirth: new Date(1997, 0, 7),
            role: "User",
            isActive: false,
        },
        {
            id: 13,
            firstName: "Daniel",
            lastName: "Jackson",
            login: "danielj",
            dateOfBirth: new Date(1990, 4, 19),
            role: "Admin",
            isActive: true,
        },
        {
            id: 14,
            firstName: "Jessica",
            lastName: "White",
            login: "jessicaw",
            dateOfBirth: new Date(1988, 2, 28),
            role: "User",
            isActive: true,
        },
        {
            id: 15,
            firstName: "Matthew",
            lastName: "Harris",
            login: "matthewh",
            dateOfBirth: new Date(1996, 8, 3),
            role: "User",
            isActive: false,
        },
        {
            id: 16,
            firstName: "Elizabeth",
            lastName: "Martin",
            login: "elizabethm",
            dateOfBirth: new Date(1985, 7, 11),
            role: "Admin",
            isActive: true,
        },
        {
            id: 17,
            firstName: "Christopher",
            lastName: "Garcia",
            login: "christopherg",
            dateOfBirth: new Date(1993, 5, 24),
            role: "User",
            isActive: true,
        },
        {
            id: 18,
            firstName: "Ashley",
            lastName: "Lee",
            login: "ashleyl",
            dateOfBirth: new Date(1991, 10, 9),
            role: "User",
            isActive: false,
        },
        {
            id: 19,
            firstName: "Andrew",
            lastName: "Perez",
            login: "andrewp",
            dateOfBirth: new Date(1989, 12, 16),
            role: "Admin",
            isActive: true,
        },
        {
            id: 20,
            firstName: "Nicole",
            lastName: "Robinson",
            login: "nicoler",
            dateOfBirth: new Date(1994, 1, 27),
            role: "User",
            isActive: true,
        },
    ];

    return { data };
};
