//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMoney.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolMoney.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bad Request: {0}.
        /// </summary>
        public static string ControllerBadRequest {
            get {
                return ResourceManager.GetString("ControllerBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Forbidden: {0}.
        /// </summary>
        public static string ControllerForbidden {
            get {
                return ResourceManager.GetString("ControllerForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Internal Server Error: {0}.
        /// </summary>
        public static string ControllerInternalError {
            get {
                return ResourceManager.GetString("ControllerInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Method Not Allowed: {0}.
        /// </summary>
        public static string ControllerMethodNotAllowed {
            get {
                return ResourceManager.GetString("ControllerMethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Not Found: {0}.
        /// </summary>
        public static string ControllerNotFound {
            get {
                return ResourceManager.GetString("ControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cookie {0} was not found..
        /// </summary>
        public static string ExceptionCookieIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionCookieIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu JWT signing key is missing..
        /// </summary>
        public static string ExceptionSigningKeyIsMissing {
            get {
                return ResourceManager.GetString("ExceptionSigningKeyIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User id is invalid..
        /// </summary>
        public static string ExceptionUserIdIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionUserIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User is not allowed to perform this operation..
        /// </summary>
        public static string ExceptionUserNotAllowed {
            get {
                return ResourceManager.GetString("ExceptionUserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to read user role..
        /// </summary>
        public static string ExceptionUserRoleNotFound {
            get {
                return ResourceManager.GetString("ExceptionUserRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ActivityId is required..
        /// </summary>
        public static string ValidatorActivityIdRequired {
            get {
                return ResourceManager.GetString("ValidatorActivityIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement content must be at least 3 characters long..
        /// </summary>
        public static string ValidatorAnnouncementContentLonger {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementContentLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement content is required..
        /// </summary>
        public static string ValidatorAnnouncementContentRequired {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement content must not exceed 4000 characters..
        /// </summary>
        public static string ValidatorAnnouncementContentShorter {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementContentShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement title must be at least 3 characters long..
        /// </summary>
        public static string ValidatorAnnouncementTitleLonger {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementTitleLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement title is required..
        /// </summary>
        public static string ValidatorAnnouncementTitleRequired {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Announcement title must not exceed 255 characters..
        /// </summary>
        public static string ValidatorAnnouncementTitleShorter {
            get {
                return ResourceManager.GetString("ValidatorAnnouncementTitleShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cron field is required..
        /// </summary>
        public static string ValidatorCronRequired {
            get {
                return ResourceManager.GetString("ValidatorCronRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cron must not exceed 255 characters..
        /// </summary>
        public static string ValidatorCronShorter {
            get {
                return ResourceManager.GetString("ValidatorCronShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start date range must be before or equal to end date range..
        /// </summary>
        public static string ValidatorDateFromBeforeOrEqualToDateTo {
            get {
                return ResourceManager.GetString("ValidatorDateFromBeforeOrEqualToDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Duration must be greater than zero..
        /// </summary>
        public static string ValidatorDurationGreaterThanZero {
            get {
                return ResourceManager.GetString("ValidatorDurationGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu End time must be after start time..
        /// </summary>
        public static string ValidatorEndTimeAfterStartTime {
            get {
                return ResourceManager.GetString("ValidatorEndTimeAfterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enrollments range must be less then 7 days..
        /// </summary>
        public static string ValidatorEnrollmentRangeExceeded {
            get {
                return ResourceManager.GetString("ValidatorEnrollmentRangeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First name must be at least 5 characters long..
        /// </summary>
        public static string ValidatorFirstNameLonger {
            get {
                return ResourceManager.GetString("ValidatorFirstNameLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First name is required..
        /// </summary>
        public static string ValidatorFirstNameRequired {
            get {
                return ResourceManager.GetString("ValidatorFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First name must not exceed 20 characters..
        /// </summary>
        public static string ValidatorFirstNameShorter {
            get {
                return ResourceManager.GetString("ValidatorFirstNameShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Group name must be at least 3 characters long..
        /// </summary>
        public static string ValidatorGroupNameLonger {
            get {
                return ResourceManager.GetString("ValidatorGroupNameLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Group name is required..
        /// </summary>
        public static string ValidatorGroupNameRequired {
            get {
                return ResourceManager.GetString("ValidatorGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Group name must not exceed 255 characters..
        /// </summary>
        public static string ValidatorGroupNameShorter {
            get {
                return ResourceManager.GetString("ValidatorGroupNameShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last name must be at least 5 characters long..
        /// </summary>
        public static string ValidatorLastNameLonger {
            get {
                return ResourceManager.GetString("ValidatorLastNameLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last name is required..
        /// </summary>
        public static string ValidatorLastNameRequired {
            get {
                return ResourceManager.GetString("ValidatorLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last name must not exceed 20 characters..
        /// </summary>
        public static string ValidatorLastNameShorter {
            get {
                return ResourceManager.GetString("ValidatorLastNameShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Long description must not exceed 4000 characters..
        /// </summary>
        public static string ValidatorLongDescriptionShorter {
            get {
                return ResourceManager.GetString("ValidatorLongDescriptionShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Message is required..
        /// </summary>
        public static string ValidatorMessageRequired {
            get {
                return ResourceManager.GetString("ValidatorMessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name field is required..
        /// </summary>
        public static string ValidatorNameRequired {
            get {
                return ResourceManager.GetString("ValidatorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name must not exceed 255 characters..
        /// </summary>
        public static string ValidatorNameShorter {
            get {
                return ResourceManager.GetString("ValidatorNameShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password must be at least 5 characters long..
        /// </summary>
        public static string ValidatorPasswordLonger {
            get {
                return ResourceManager.GetString("ValidatorPasswordLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password is required..
        /// </summary>
        public static string ValidatorPasswordRequired {
            get {
                return ResourceManager.GetString("ValidatorPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password must not exceed 255 characters..
        /// </summary>
        public static string ValidatorPasswordShorter {
            get {
                return ResourceManager.GetString("ValidatorPasswordShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Role must be one of: {0}.
        /// </summary>
        public static string ValidatorRoleFromRolesList {
            get {
                return ResourceManager.GetString("ValidatorRoleFromRolesList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Short description must not exceed 1000 characters..
        /// </summary>
        public static string ValidatorShortDescriptionShorter {
            get {
                return ResourceManager.GetString("ValidatorShortDescriptionShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start time must be before end time..
        /// </summary>
        public static string ValidatorStartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("ValidatorStartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start time is required..
        /// </summary>
        public static string ValidatorStartTimeRequired {
            get {
                return ResourceManager.GetString("ValidatorStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subject must be at least 3 characters long..
        /// </summary>
        public static string ValidatorSubjectLonger {
            get {
                return ResourceManager.GetString("ValidatorSubjectLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subject is required..
        /// </summary>
        public static string ValidatorSubjectRequired {
            get {
                return ResourceManager.GetString("ValidatorSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Subject must not exceed 255 characters..
        /// </summary>
        public static string ValidatorSubjectShorter {
            get {
                return ResourceManager.GetString("ValidatorSubjectShorter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total capacity must be greater than zero..
        /// </summary>
        public static string ValidatorTotalCapacityGreaterThanZero {
            get {
                return ResourceManager.GetString("ValidatorTotalCapacityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User id is required..
        /// </summary>
        public static string ValidatorUserIdRequired {
            get {
                return ResourceManager.GetString("ValidatorUserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Username must be at least 5 characters long..
        /// </summary>
        public static string ValidatorUsernameLonger {
            get {
                return ResourceManager.GetString("ValidatorUsernameLonger", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Username is required..
        /// </summary>
        public static string ValidatorUsernameRequired {
            get {
                return ResourceManager.GetString("ValidatorUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Username must not exceed 20 characters..
        /// </summary>
        public static string ValidatorUsernameShorter {
            get {
                return ResourceManager.GetString("ValidatorUsernameShorter", resourceCulture);
            }
        }
    }
}
